### create user 1
POST http://localhost:4444/api/user

{
"user":"1",
"password":"1"
}

### create user 2
POST http://localhost:4444/api/user

{
"user":"2",
"password":"2"
}

### create session 1
POST http://localhost:4444/api/session

{
"user_id":2,
"password":"1"
}

### create session 2
POST  http://localhost:4444/api/session

{
"user_id":3,
"password":"2"
}

### get file
GET http://localhost:4444/api/files/2/test.txt

{
"token":"1"
}

### post file
POST http://localhost:4444/api/files/2/test.txt

{
"token":"1",
"file_data":"test some data"
}

### put file
PUT http://localhost:4444/api/files/2/test.txt

{
"token":"1",
"file_data":"updated data"
}

### delete file
DELETE http://localhost:4444/api/files/2/test.txt

{
"token":"1"
}

### give access
POST http://localhost:4444/api/give_access

{
"token":"1",
"user_id":3,
"path":"test.txt",
"rights":"r"
}

### get file
GET http://localhost:4444/api/files/2/test.txt

{
"token":"2"
}

### put file
PUT http://localhost:4444/api/files/2/test.txt

{
"token":"2",
"file_data":"updated data 20"
}

### give access
POST http://localhost:4444/api/give_access

{
"token":"1",
"user_id":3,
"path":"test.txt",
"rights":"rw"
}